### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hparfr** [akretion/ak#93]
Some ideas:

- [ ] `ak sparse` is implemented since 3 years, it's now time to call it by default
- [ ] `ak sort` to sort a spec alphabetically
- [ ] allow to use both indirect ref/pull syntax and direct branch name
- [ ] be more explicit about missing modules
- [x] find if missing modules are filtrered due to sparse
- [ ] use worktree to speed up
